kubecfg/kubit

.github/workflows/rust.yml
config/crd/bases/kubecfg.dev_appinstances.yaml
src/main.rs
src/resources.rs

Building from https://github.com/kubecfg/kubit/pull/7#discussion_r1273617933
This writes the `AppInstance` CRD directly into the file, meaning we can simply update the manifests with `cargo run -- manifests`.
---
```rust
// src/resources.rs
pub struct AppInstanceSpec {
pub package: Package,
pub test: String, // adding this field
pub image_pull_secrets: Option<Vec<LocalObjectReference>>,
}
```
And execute `cargo run -- manifests --crd-dir config/crd/bases`, then we see
```
git status --short
M config/crd/bases/kubecfg.dev_appinstances.yaml
M src/resources.rs
```
```yaml
required:
- package
+  - test
```
When running simply `cargo run -- manifests`, we are writing to `stdout` as before.

feat: update manifests command to write CRDs to disk

---

src/controller.rs
src/lib.rs
src/main.rs

Fetches the OCI artifact manifests and parses the config created by `kubecfg pack`.
It doesn't do anything yet with the info and it only handles unauthenticated repo.

feat: Fetch OCI metadata

---

config/crd/bases/kubecfg.dev_appinstances.yaml
src/main.rs

At the moment, if we run the `manifests` command, this is tied entirely to only our `AppInstance` CRD. This is being changed so that we have a single place to reference the CRDs (within the outer `vec!` macro), these can be updated as we add CRDs.
We're adding the YAML delimiter (`---`) to signify that there may be multiple documents.

refactor: unify code path for `--crd-dir` flag, writing to a `File` and `stdout`

---

config/crd/bases/kubecfg.dev_appinstances.yaml
src/resources.rs

I misunderstood what schema would k8s accept for arbitrary subtree.
Turns out we need `x-kubernetes-preserve-unknown-fields`
```yaml
apiVersion: v1
items:
- apiVersion: kubecfg.dev/v1alpha1
kind: AppInstance
metadata:
creationTimestamp: "2023-07-27T15:29:52Z"
generation: 4
name: influxdb
namespace: influxdb
resourceVersion: "5036"
uid: 74f45619-593d-4122-85dd-136ca96c027d
spec:
imagePullSecrets:
- name: gar-docker-secret
package:
apiVersion: influxdata.com/v1alpha1
image: oci.influxdata.com/influxdb:20230718
spec:
catalog: {}
images: {}
ingesterStorage: {}
ingress: {}
objectStore: {}
kind: List
metadata:
resourceVersion: ""
```
funny enough, once we fix the CRD, the apiserver re-surfaces the fields without having to reapply the reource! the fields weren't lost:
```yaml
apiVersion: v1 …
```

fix: Add x-kubernetes-preserve-unknown-fields

---

src/controller.rs

The `sinker` repository was used to scaffold the Rust operator, but this naming is not relevant for us here and could be confusing seeing a completely new name in this function.
We'll fill out this `error_policy` func later on.

chore: remove `sinker` reference

---

src/controller.rs
src/render.rs

The intention here is that the `kubecfg` step will be an `initContainer` (not done yet) which will render our given OCI bundle, which contains manifests. 
Eventually it will write the manifests into a file. This file will be accessible to the (currently non-existent) `apply` step as it will have been written to an `emptyDir` that is shared by the `Job`.

feat: render manifests via `kubecfg`

---

config/crd/bases/kubecfg.dev_appinstances.yaml
src/apply.rs
src/controller.rs
src/render.rs
src/resources.rs

This PR implements the basic logic for the applier loop:
1. spawn a job that renders and applies the templates
2. wait until the job has run
3. capture and report the logs
The main thing that is missing here is throttling. Right now the controller will just create a new job right away.
Here is how to see the logs when the job fails:
```
$ kubectl -n influxdb get appinstances influxdb -o yaml | yq .status
lastLogs:
fetch-app-instance: |
rendered ok
render-manifests: "trying next host\nerror reading data:,%28import%20%22oci:%2F%2Fus-docker.pkg.dev%2Finfluxdb2-artifacts%2Fclustered%2Finfluxdb:20230727-503750%22%29%20+%20%28%7BappInstance_+:import%20%22%2Foverlay%2Fappinstance.json%22%7D%29: RUNTIME ERROR: Get \"oci://us-docker.pkg.dev/influxdb2-artifacts/clustered/influxdb:20230727-503750/\": …
```

Follow the job, capture the logs, delete the job, and repeat

---

.github/workflows/release.yml
.github/workflows/rust.yml

Uses the [`github.ref_name`](https://docs.github.com/en/actions/learn-github-actions/contexts) as the tag to push a tagged image into GHCR, e.g. `v0.0.1`.
> The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub.

ci: add simple release step on tagged branch

---

.github/workflows/release.yml
.github/workflows/rust.yml

I tried a draft of this PR where we pushed to GHCR also during the PR build, so that I could try out depot GHCR auth.
(kudos to @kylegalbraith and @jacobwgillespie and everybody else on the depot team, you got a happy user today!)
Now I switched back to the original code that only pushed builds in `main` branch and releases.
I also updated the release pipeline, but that's hard to debug in a PR

chore: Use depot remote builds instead of buildx

---

.github/workflows/rust.yml

Our current CI fails with 
```
Error: buildx failed with: ERROR: Multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```
However, we have since moved to `depot` for their speedy multi-arch images. So our regular `docker/build-push-action` needs changing to the `depot` specific one.

ci: use depot for release image push

---

.github/workflows/rust.yml

We don't want the GitHub release portion in for now, we only want images being pushed into GHCR.

ci: remove github release step

---

.github/workflows/rust.yml

I was using my personal depot account to evaluate depot remote docker build. I'm happy with it and I created an account for the kubecfg org

Switch to kubecfg depot org

---

Cargo.lock
Cargo.toml
README.md
kustomize/manager/kustomization.yaml

I realized there is another place where the version is stored: Cargo.toml (which is used by `kubit -V`)

chore: Prepare for release v0.0.5

---

src/apply.rs
src/lib.rs
src/local.rs
src/main.rs
src/render.rs
src/scripting.rs

kubit is "just a thin" frontend around kubecfg that combine a template and an "app instance" yaml.
But nevertheless, even if in principle one can just invoke kubecfg with the appropriate flags to render and apply a template there are quite a bunch of flags.
it would be nice if we could just use kubit as helper  like that:
```console
kubit apply myappinstance.yaml
```
or even as a kubectl plugin!
```console
kubectl kubit apply myappinstance.yaml
```
--
This PR reuses the existing functions that generate kubecfg and kubectl invocations.
It creates a new module called `scripting` that helps with composing simple bash scripts. It handles argument quoting and adding common preamble like shebang etc.

Implement kubit apply command

---

src/controller.rs
src/local.rs
src/render.rs
src/scripting.rs

Before:
```bash
#!/bin/bash
set -euo pipefail
manifests=$(mktemp -d)
export KUBECTL_APPLYSET=true
kubecfg \
show \
--alpha \
'--reorder=server' \
oci://us-docker.pkg.dev/influxdb2-artifacts/clustered/influxdb:20230814-529785 \
--overlay-code-file \
'appInstance_=/Users/mkm/tmp/appinstance.yaml' \
--export-dir \
"${manifests}" \
--export-filename-format \
'{{printf "%03d" (resourceIndex .)}}-{{.apiVersion}}.{{.kind}}-{{default "default" .metadata.namespace}}.{{.metadata.name}}'
kubectl \
apply \
-f \
"${manifests}" \
-n \
influxdb \
--server-side \
--prune \
--applyset \
influxdb \
--force-conflicts \
'-v=2'
```
After:
```bash
#!/bin/bash
set -euo pipefail
export KUBECTL_APPLYSET=true
kubecfg \
show \
--alpha \
'--reorder=server' \ …
```

chore: Use pipe instead of temp files

---

README.md

This is a bit better since it allows the user to put whatever name and namespace they want in the yaml file and have still the documentatied snipped to be actually working and yet terse

doc: use get -f file.yaml

---

README.md
src/local.rs
src/main.rs

The `kubit apply -f foo.yaml`  command is too similar to `kubectl apply -f foo.yaml` and it may be surprising that it doesn't actually apply the foo.yaml CR itself but instead it runs the operator logic locally.
Wrapping that command (and possibly others) under a `local` command group is likely going to be much more intuitive to users.

Wrap apply under local subcommand

---

src/local.rs
src/render.rs

Demo:
```bash
kubit local apply ~/tmp/appinstance.yaml --dry-run=diff --package-image=file://$HOME/myproject/main.jsonnet
```
This is the equivalent of:
```
kubecfg show ~/myproject/main.jsonnet --overlay-code-file appInstance=~/tmp/appinstance.yaml | kubectl diff -f -
```
but it works more naturally if you're already in the flow of using `kubit local` and thinking of your app instance yaml file as your main entry point and _occasionally_ you want to quickly try out what it would be like using the jsonnet source files before pushing them to the OCI registry
---
This PR makes two changes:
1. allows file:// urls in the `.spec.package.image` field.
2. adds a `--package-image` CLI flag to the `apply` command.
You don't have to use the --package-image flag, you can also edit your YAML file and …

feat: Allow to quickly override package image from CLI

---

src/controller.rs
src/main.rs

Sometimes you want to pause an appinstance so that the in-incluster operator ignores it but then you want to run a local in-development version of the controller so that it ignores all other instances except that one

feat: Only paused

---

kustomize/rbac/role.yaml
src/controller.rs

`kubectl apply --prune` can delete resources that are no longer referenced in the input manifests.
However we forgot to add the `delete` verb to the `kubit-applier` role.
Before:
```
error: pruning Job.batch influxdb/token-gen-ac6502b4: jobs.batch "token-gen-ac6502b4" is forbidden: User "system:serviceaccount:influxdb:kubit-applier" cannot delete resource "jobs" in API group "batch" in the namespace "influxdb"
```
After:
```
...
job.batch/token-gen-ac6502b4 pruned
```

fix: fix rbac so it can prune resources 

---

Cargo.lock
Cargo.toml

The kubert project was temporarily struggling to update a dependency and we temporarily forked it in https://github.com/kubecfg/kubert
Now the desired change is upstream so we can remove the usage of the temporary fork

chore: Update kubert

---

README.md

With the prevalence of tools such as `helm` and `kustomize`, it might be unclear as to why there is any need for `kubit` to exist at all.
By adding this motivation section, it makes it clearer that `kubit` is aimed at being an abstraction above those, decoupling the tools used to build and install the package.

docs: add motivation section to `README.md`

---

src/apply.rs
src/controller.rs
src/local.rs

If you want to simulate how would the in-cluster kubit controller apply a package that you have not yet pushed you can now run:
```bash
kubit local apply appinstance.yaml --package-image file://$PWD/main.jsonnet --as system:serviceaccount:influxdb:kubit-applier
```

feat: Add --as to local apply

---

src/helpers.rs
src/lib.rs
src/main.rs
src/metadata.rs

Currently the kubit controller needs to run `kubectl get -o json >outputfile` to fetch the appinstance. This requires a shell.
The official kubectl image from the k8s repo doesn't come with a shell, so we have to use the bitnami image. I like the bitnami image but I'd prefer to be able to use any kubectl image, especially the official one.
Furthermore, the kubectl get approach also fetches the status. I think the template engine shouldn't have access to the status field that contains it's own previous output (in the logs).
This PR just adds the `kubit helpers fetch-app-instance` command (which is hidden from casual CLI users) and doesn't change the controller to actually using it.

feat: Add command to fetch appinstance

---

Cargo.lock
Cargo.toml
Dockerfile

Closes #115 
Tested locally:
```bash
$ depot build --project v8n5whjnsb --platform linux/amd64,linux/arm64 . -t mkmik/kubit:latest --load 
$ docker run --rm mkmik/kubit:latest --version
0.0.9
```
TODO: add a step in CI that loads the image and performs a simple smoke test like that

Fix rustls

---

src/local.rs

Demo:
```console
$ kube local apply foo.yml --diff
diff -u -N /var/folders/zp/pk0v2q4x39z43k91vst1_jsc0000gn/T/LIVE-1086344607/apps.v1.Deployment.influxdb.iox-shared-querier /var/folders/zp/pk0v2q4x39z43k91vst1_jsc0000gn/T/MERGED-221010015/apps.v1.Deployment.influxdb.iox-shared-querier
--- /var/folders/zp/pk0v2q4x39z43k91vst1_jsc0000gn/T/LIVE-1086344607/apps.v1.Deployment.influxdb.iox-shared-querier     2023-09-04 17:05:22
+++ /var/folders/zp/pk0v2q4x39z43k91vst1_jsc0000gn/T/MERGED-221010015/apps.v1.Deployment.influxdb.iox-shared-querier    2023-09-04 17:05:22
@@ -4,7 +4,7 @@
annotations:
deployment.kubernetes.io/revision: "7"
creationTimestamp: "2023-08-16T08:09:34Z"
-  generation: 25
+  generation: 26
.....
Apply? [y/N] n
$
```
If you type `y` or `Y` instead, it will continue and …

feat: Add --diff flag to local apply

---

.github/workflows/rust.yml

This was taken directly from the [`kubecfg`](https://github.com/kubecfg/kubecfg/blob/4c033328ff911209913d7694a08fcd1ee85ecadd/.github/workflows/go.yml#L87-L105) release pipeline, with a few line removals where we do not use them in this repository.
We currently only publish an image into `ghcr.io`, it'll be nice to have proper GitHub releases where we can place changelogs or any other necessary information about a release of the project.

ci: add `create_release` step

---

kustomize/manager/manager.yaml
src/main.rs

Whilst I can understand that this is along the lines of "Kubit's kubit image", as opposed to the `kubecfg` specific one, I think the double `KUBIT` in the environment variable doesn't make too much sense ~~and the intention of `KUBIT_IMAGE` is already clear.~~
Perhaps `KUBIT_CONTROLLER_IMAGE` instead? If we want to be extra clear. (**edit:** I've swapped to this now)

fix: remove duplicate `KUBIT` naming in env vars

---

.github/workflows/rust.yml

Closes https://github.com/kubecfg/kubit/issues/117
Runs a smoke test of the built container.
We're adding the `docker/setup-buildx-action` here as the `depot` specific action only makes the `depot` CLI available.
We require the `load: true` to be set in order to populate the `docker` cache with our newly built image, [`depot build`](https://github.com/depot/cli#depot-build) reference.
> By default, `depot build` will leave the built image in the remote builder cache. If you would like to download the image to your local Docker daemon (for instance, to `docker run` the result), you can use the `--load` flag.

ci: add minimal smoke test

---

src/controller.rs

This is something which I've noticed when running locally, such that the `activeDeadlineSeconds` countdown begins as soon as the `Pod` starts running, meaning that the task can be half-completed and then terminated with `DeadlineExceeded`.
Whilst this isn't a huge problem because the tasks can be retried, it also might be confusing to see the `Pod` itself fail and then be restarted, only to succeed on the 2nd or 3rd attempt. I believe we can easily get around this by bumping the time to complete the `Pod`'s work itself:
**Note:** This is being set on the `Pod.spec` too, rather than the `Job.spec`:
```
kubectl explain pod.spec.activeDeadlineSeconds
...
duration in seconds the pod may be active on the node relative to
StartTime before the system will actively try to mark it failed and kill …
```

fix: bump `active_deadline_seconds` to 180

---

.github/workflows/package_demo.yml
.github/workflows/rust.yml
src/render.rs
tests/fixtures/fake-package.yml
tests/fixtures/shell.jsonnet
tests/local_apply.rs

The current fixture from `gcr.io/mkm-cloud` was created from a laptop and pushing into a public registry, we can use the same `jsonnet` file and bring it under `kubit` so that we control it.
An issue we have at the moment is that the package metadata on the image is out of date, it was built with an older version of `kubecfg` which is causing a test to fail that I'm writing in another branch, this is a necessary yak to shave in order to have a consistent package that we can assert against.
This PR gives us the same thing, but from within `kubit` and pushed into the `ghcr.io` registry instead for keeping everything contained to this project.

feat: include fake package demo from `kubecfg pack` for tests

---

.github/workflows/rust.yml
src/render.rs
tests/local_apply.rs

This builds from both https://github.com/kubecfg/kubit/pull/185 and https://github.com/kubecfg/kubit/pull/210. It adds another integration test, but this time for the `--dry-run render` output, ensuring that the rendered output contains some known items that we expect to see, such as the `AppInstance` resource.
I was considering running a `serde_yaml` serialisation here and testing equality but I think the simple `.contains()` does what we want with minimal complexity, although I'm happy to alter this if needs be.

feat: add `--dry-run render` test

---

kustomize/crd/bases/kubecfg.dev_appinstances.yaml
src/resources.rs

I initially used our own LocalObjectReference definition because I didn't know I could enable the `schemars` feature on the `k8s-openapi` dependency. I enabled that feature in some past PR but I forgot to get rid of this copy.

chore: Use k8s api LocalObjectReference

---

src/apply.rs
src/local.rs
src/render.rs
tests/local_apply.rs

Building from https://github.com/kubecfg/kubit/pull/157, I introduced a `docker run` flow for `kubit local apply`.
I was half-way there in that I already added the `is_local` check, but didn't make this a flag for "opt-in" behaviour.
This changes that to opt-in via the `--docker` flag and has been renamed for consistency.

feat: add `--docker` flag for `local apply` use 

---

src/local.rs

In https://github.com/kubecfg/kubit/pull/177 some refactoring was done and my review missed the fact that `DryRun::Diff` is used when being passed to `write_script`, this enables the `--diff` feature to run in the correct order.
At the moment, it always drops into the regular `write_script` flow because it is not possible to pass both `--dry-run diff` and `--diff` together, so `None` is always passed to `write_script`. Thus causing the "apply" to run before the "diff" in our current flow, which is incorrect.
---
The changes are applied first, there is now no diff to show.
```bash
cargo run -- local apply tests/fixtures/fake-package.yml --diff
Compiling kubit v0.0.11 (/home/influx/work/kubit)
Finished dev [unoptimized + debuginfo] target(s) in 9.97s
Running `target/debug/kubit local apply …
```

fix: `--diff` flag for `local apply`

---

src/render.rs

By missing this off, you can see:
```
E1123 16:36:56.360452       1 client.go:227] couldn't get current server API group list: Get "https://0.0.0.0:51339/api?timeout=32s": dial tcp 0.0.0.0:51339: connect: connection refused
E1123 16:36:56.362520       1 client.go:227] couldn't get current server API group list: Get "https://0.0.0.0:51339/api?timeout=32s": dial tcp 0.0.0.0:51339: connect: connection refused
```
as the container is trying to find the controlplane to run against. This _eventually_ works, but is not very pretty.
The `kubectl` container already uses this, but I missed it off this one for unknown reasons.

fix: use `--network host` for `kubecfg show` step

---

src/docker_config.rs

We've seen a few mentions of a decoding error of a provided `.dockerconfigjson`, which has been tracked down to this `.decode` call.
I've been able to reproduce this too by using a provided config and I get back the similar error
```
Cannot launch installation job: Error decoding docker config JSON: Error decoding base64 field inside docker config auth section: Invalid padding
```
After I added this fallback, it fixes the error.
**Before:**
```
2023-12-05T12:20:27.682058Z  INFO kubit::controller: state=Idle
2023-12-05T12:20:27.714644Z  INFO kubit::controller: getting image pull credentials
2023-12-05T12:20:27.760586Z  INFO kubit::controller: status patched
2023-12-05T12:20:27.799031Z  INFO kubit::controller: status patched
2023-12-05T12:20:27.799296Z  WARN kubit::controller: reconcile …
```

fix: use `URL_SAFE` decoding mechanism for `DockerConfig`

---

src/docker_config.rs

Alteration to an oversight made in https://github.com/kubecfg/kubit/pull/284
See https://github.com/kubecfg/kubit/pull/284#discussion_r1415556009 for a little more detail.

fix: use `STANDARD` decoding for base64

---

kustomize/crd/bases/kubecfg.dev_appinstances.yaml
src/resources.rs

This adds additional printer columns for the `kubectl get` output of an `AppInstance`, making the feedback a little more clear for what has happened and could also help users quickly spot a problem with the regular output, rather than being required to always check the entire YAML input.
Before this change, the output looked like this:
```
kubectl get appinstances.kubecfg.dev -n test
NAME   AGE
test   4m34s
```
Once the additional print columns are included, this now looks like this:
```
kubectl get appinstances.kubecfg.dev
NAME   IMAGE                                   APIVERSION           PAUSED   REASON      STATUS
test   ghcr.io/kubecfg/kubit/package-demo:v1   kubit.dev/v1alpha1   false    JobFailed   False
```
---
I've also removed the minor serialisation skip on the `spec.pause` as …

feat: add kubectl print columns

---

.github/workflows/rust.yml

Helps with https://github.com/kubecfg/kubit/pull/397
We run into authentication errors when forks try to build/push into
Depot as they do not originate from the kubecfg project. This also saves
the addition for everybody being added to the `kubecfg` project in order
to contribute to `kubit` :smile:
For reference, I remember [I ran into the same thing](https://github.com/kubecfg/kubecfg/pull/287) awhile back when I
first contributed to `kubecfg`, but we can also see this with `kubit`.

ci: dont push to depot on fork

---

src/helpers.rs

The `kubit helpers fetch-app-instance` command is used to populate `/overlay/appinstance.json` during the apply job. This command fetches the current state of the AppInstance with the API but does not strip out managedFields. This leads to kubectl returning
`Error from server (BadRequest): metadata.managedFields must be nil` when trying to apply the manifests.
<details>
<summary>Before</summary>
```json
{
"apiVersion": "kubecfg.dev/v1alpha1",
"kind": "AppInstance",
"metadata": {
"creationTimestamp": "2024-04-15T22:33:56Z",
"finalizers": [
"kubecfg.dev/appinstance-cleanup"
],
"generation": 2,
"labels": {
"kustomize.toolkit.fluxcd.io/name": "flux-system",
"kustomize.toolkit.fluxcd.io/namespace": "flux-system"
},
"managedFields": [
{
"apiVersion": "kubecfg.dev/v1alpha1",
"fieldsType": …
```

fix: Remove managedFields from AppInstance

---

Cargo.lock
Cargo.toml
README.md
kustomize/manager/kustomization.yaml

It's been awhile since we've done a release and there's a been a fix and a few niceties since `0.0.14` that we should put out there :rocket:

chore(release): prep for `0.0.15`

---

src/helpers.rs

This fixes the following error when applying manifests:
`apply-manifests error: ApplySet label "applyset.kubernetes.io/part-of" already set in input data`
<details><summary>Before</summary>
<p>
```json
{
"apiVersion": "kubecfg.dev/v1alpha1",
"kind": "AppInstance",
"metadata": {
"creationTimestamp": "2024-04-22T15:32:01Z",
"finalizers": [
"kubecfg.dev/appinstance-cleanup"
],
"generation": 2,
"labels": {
"applyset.kubernetes.io/part-of": "applyset-mBM9N2j2qchpaBrvdpdvR14sxslSY3xXQErluXJpNgE-v1",
"kustomize.toolkit.fluxcd.io/name": "flux-system",
"kustomize.toolkit.fluxcd.io/namespace": "flux-system"
},
"name": "podinfo",
"namespace": "default",
"resourceVersion": "16394167",
"uid": "52d8b18a-dc24-4d73-9086-a3a308b5da6a"
},
"spec": {
"package": {
"image": "***/podinfo:v0.0.3",
"apiVersion": …
```

fix: remove label already set in input data

---

Cargo.lock
Cargo.toml
README.md
kustomize/manager/kustomization.yaml

We need a new release that incorporates #458.

chore(release): prep for `0.0.17`

---

src/controller.rs

In order to delete CRDs that it creates (ie when doing cleanup finalization for an AppInstance), `kubit-applier` needs delete permission.
```
kubit-cleanup-influxdb-c8g6l cleanup-manifests error: pruning CustomResourceDefinition.apiextensions.k8s.io licenses.influxdata.io: customresourcedefinitions.apiextensions.k8s.io "licenses.influxdata.io" is forbidden: User "system:serviceaccount:influxdb:kubit-applier" cannot delete resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```
This PR adds the necessary `delete` permission to the existing `ClusterRole`. It also renames some functions and moves their calling location as a bit of added cleanup.

fix: kubit-applier SA needs CRD delete permission

---

docs/release-process.md
scripts/prepare_release.sh

Closes https://github.com/kubecfg/kubit/issues/483
Adds some short notes on how someone can conduct a release of `kubit`.

docs: add short note for release process

---

README.md

I suspect that this has been wrong for awhile since it got left behind, so any `sed -i ...` usage would have missed it too when going from `0.0.14` to `0.0.15` and so forth.
With this aligned, further releases will also bump this tag too :+1:

fix: tag for single-namespace

---

Cargo.lock
Cargo.toml
README.md
kustomize/manager/kustomization.yaml

The new preparation script works very nicely here too, great convenience :rocket: 
```
scripts/prepare_release.sh 0.0.19
Latest tag: v0.0.18
Latest version: 0.0.18
Desired version: 0.0.19
Locking 1 package to latest compatible version
Updating kubit v0.0.18 (/home/influx/work/kubit) -> v0.0.19
Downloaded tower-layer v0.3.3
...more cargo things
```

chore: prepare for `0.0.19`

---

Dockerfile
kustomize/single-namespace/kustomization.yaml
src/controller.rs

This implements some fixes for the single-namespace mode. The original behavior attempts to install the CustomResourceDefinition and ClusterRoles regardless of whether kubit is running in single-namespace mode. Since these require "root" scoped permissions, this would prevent kubit from applying the app-instance ConfigMap.

fix: enable single-namespace mode

---

src/controller.rs

This fixes an issue where the ClusterRole/ClusterRoleBinding oscillates between namespaces when multiple AppInstances are deployed into multiple namespaces.

fix: deploy ClusterRoleBinding per namespace
