kubecfg/kubit

src/controller.rs, src/lib.rs, src/render.rs
work in progress but it's safe to merge
=> feat: (partial feature) Create a Job that runs kubecfg

src/controller.rs, src/render.rs
This simplifies things a bit since we don't have to worry about cleaning up configmaps
=> Fetch the app instance in init container

.github/workflows/release.yml
This was previously not a valid name :facepalm:
=> fix: ci typo

config/rbac/role.yaml
I didn't test #51 inside a docker image...
=> fix: Fix RBAC for image pull secrets

README.md, kustomize/manager/kustomization.yaml
changelog:
* log something at startup
=> chore: Prepare for v0.0.4

Cargo.lock, Cargo.toml, kustomize/crd/bases/kubecfg.dev_appinstances.yaml, src/controller.rs, src/resources.rs
I'm not super happy about the cleanliness of the status update code. I'll cleanup in a follow up PR
=> feat: report status conditions

Cargo.lock, Cargo.toml, README.md, kustomize/manager/kustomization.yaml
Prepare for `v0.0.9` tag for a new release.
=> chore: prep for v0.0.9 release

src/apply.rs, src/controller.rs, src/local.rs, src/main.rs, src/metadata.rs, src/oci.rs, src/resources.rs
=> chore: Minor error handling improvement

kustomize/manager/kustomization.yaml, kustomize/manager/manager.yaml, kustomize/manager/nameReferences.yaml, src/controller.rs, src/docker_config.rs, src/main.rs, src/render.rs
This allows us to use official kubectl images without a shell
=> feat: Use kubit helper fetch-app-instance

Cargo.lock, Cargo.toml, README.md, kustomize/manager/kustomization.yaml
Mainly to get a hot fix for linux (https://github.com/kubecfg/kubit/pull/161)
=> chore: Prep for 0.0.11 release

src/metadata.rs
Addresses https://github.com/kubecfg/kubit/pull/157/files#r1336123179 review comment
=> chore: Expose fetch_package_config_local_auth method in metadata.rs

src/controller.rs
Fixes https://github.com/kubecfg/kubit/issues/231
=> fix: Fix hard coded pull secret name

Cargo.lock, Cargo.toml, README.md, kustomize/manager/kustomization.yaml
=> chore: prep for `0.0.12`

Cargo.lock, Cargo.toml, README.md, kustomize/manager/kustomization.yaml
=> chore: prep for `0.0.13`

Cargo.lock, Cargo.toml, README.md, kustomize/manager/kustomization.yaml
Prep new release which includes `AppInstance` deletion.
=> chore(release): prep for `0.0.14`

Cargo.lock, Cargo.toml, src/main.rs
subsumes https://github.com/kubecfg/kubit/pull/283 and https://github.com/kubecfg/kubit/pull/303
=> Upgrade kube

Cargo.lock, Cargo.toml, README.md, kustomize/manager/kustomization.yaml
=> chore(release): prep for `0.0.16`

src/controller.rs
At InfluxData we are using kubit to deploy manifests that includes a `CustomResourceDefinition`. This PR adds the necessary `ClusterRole` and `ClusterRoleBinding` for the `kubit-applier` to do this.
=> fix(controller): kubit-applier job needs to be able to create/patch/list/get CRDs

Cargo.lock, Cargo.toml, README.md, kustomize/manager/kustomization.yaml
We need a new release for #476
=> chore(release): prep for 0.0.18

docs/how-it-works.md, src/apply.rs, src/controller.rs, src/delete.rs, src/local.rs, src/main.rs, src/render.rs, tests/local_apply.rs
Closes https://github.com/kubecfg/kubit/issues/506
=> feat: make kubectl/kubecfg images configurable
